import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CursorProvider from "@/components/CursorContext";
// import Transition from "@/components/Transition";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" className="!scroll-smooth">
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </head>
        <body className={inter.className}>
          <CursorProvider>
            {/* <Transition /> */}
            <Navbar />
            {children}
            <Footer />
          </CursorProvider>
        </body>
      </html>
    </>
  );
}
